source 'https://rubygems.org'

gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-compass', '>= 4.0.0'
gem 'jquery-middleman'
gem 'middleman-sprockets', '~> 4.0.0.rc.1'
gem 'middleman-autoprefixer'
gem 'flexboxgrid', '~> 0.0.3'
gem 'font-awesome-sass', '~> 4.7.0'
gem 'guard'
gem 'guard-middleman'
gem 'guard-livereload'
gem 'listen', '~> 3.0'
gem 'guard-shell'
